# Generated by Django 5.1.4 on 2025-12-28 09:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#007bff', max_length=7)),
                ('icon', models.CharField(default='device', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='monitoring.devicegroup')),
            ],
            options={
                'verbose_name': 'Device Group',
                'verbose_name_plural': 'Device Groups',
                'db_table': 'monitoring_device_group',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='monitoring.location')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'monitoring_location',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('device_name', models.CharField(blank=True, max_length=255)),
                ('device_type', models.CharField(choices=[('ap', 'Access Point'), ('sm', 'Subscriber Module'), ('switch', 'Switch'), ('router', 'Router'), ('firewall', 'Firewall'), ('server', 'Server'), ('other', 'Other')], default='other', max_length=20)),
                ('ap_name', models.CharField(blank=True, max_length=255, verbose_name='AP Name')),
                ('cid', models.CharField(blank=True, max_length=100, verbose_name='CID')),
                ('ap_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='AP IP')),
                ('sm_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='SM IP')),
                ('monitoring_enabled', models.BooleanField(default=True)),
                ('ping_enabled', models.BooleanField(default=True)),
                ('snmp_enabled', models.BooleanField(default=False)),
                ('snmp_community', models.CharField(blank=True, default='public', max_length=100)),
                ('snmp_version', models.CharField(choices=[('1', 'v1'), ('2c', 'v2c'), ('3', 'v3')], default='2c', max_length=10)),
                ('status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('warning', 'Warning'), ('maintenance', 'Maintenance'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_check', models.DateTimeField(blank=True, null=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledgment_comment', models.TextField(blank=True)),
                ('in_maintenance', models.BooleanField(default=False)),
                ('maintenance_start', models.DateTimeField(blank=True, null=True)),
                ('maintenance_end', models.DateTimeField(blank=True, null=True)),
                ('maintenance_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_hosts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='monitoring.devicegroup')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='monitoring.location')),
            ],
            options={
                'verbose_name': 'Host',
                'verbose_name_plural': 'Hosts',
                'db_table': 'monitoring_host',
                'ordering': ['hostname'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('ping_latency', 'Ping Latency'), ('ping_loss', 'Ping Loss'), ('snmp_cpu', 'CPU Usage'), ('snmp_memory', 'Memory Usage'), ('snmp_interface_in', 'Interface In'), ('snmp_interface_out', 'Interface Out'), ('snmp_temperature', 'Temperature'), ('custom', 'Custom Metric')], max_length=50)),
                ('metric_name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('interface', models.CharField(blank=True, max_length=100)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='monitoring.host')),
            ],
            options={
                'verbose_name': 'Monitoring Metric',
                'verbose_name_plural': 'Monitoring Metrics',
                'db_table': 'monitoring_metric',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('suppressed', 'Suppressed')], default='active', max_length=20)),
                ('check_type', models.CharField(max_length=50)),
                ('metric_name', models.CharField(blank=True, max_length=100)),
                ('threshold_value', models.FloatField(blank=True, null=True)),
                ('current_value', models.FloatField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledgment_comment', models.TextField(blank=True)),
                ('notifications_sent', models.JSONField(blank=True, default=list)),
                ('last_notification', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.host')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'db_table': 'monitoring_alert',
                'ordering': ['-first_seen'],
                'indexes': [models.Index(fields=['host', 'status'], name='monitoring__host_id_ef63d6_idx'), models.Index(fields=['severity', 'status'], name='monitoring__severit_1e6a2c_idx'), models.Index(fields=['first_seen'], name='monitoring__first_s_fe1a7d_idx'), models.Index(fields=['status'], name='monitoring__status_d438e1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='host',
            index=models.Index(fields=['ip_address'], name='monitoring__ip_addr_7f7eef_idx'),
        ),
        migrations.AddIndex(
            model_name='host',
            index=models.Index(fields=['status'], name='monitoring__status_5804fd_idx'),
        ),
        migrations.AddIndex(
            model_name='host',
            index=models.Index(fields=['location'], name='monitoring__locatio_f22858_idx'),
        ),
        migrations.AddIndex(
            model_name='host',
            index=models.Index(fields=['group'], name='monitoring__group_i_64a432_idx'),
        ),
        migrations.AddIndex(
            model_name='host',
            index=models.Index(fields=['last_check'], name='monitoring__last_ch_0adf32_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='host',
            unique_together={('hostname', 'ip_address')},
        ),
        migrations.AddIndex(
            model_name='monitoringmetric',
            index=models.Index(fields=['host', 'metric_type', 'timestamp'], name='monitoring__host_id_93d853_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringmetric',
            index=models.Index(fields=['timestamp'], name='monitoring__timesta_a57f02_idx'),
        ),
    ]
