# Generated by Django 5.1.4 on 2025-12-30 07:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='ping_critical_latency',
            field=models.FloatField(default=500.0, help_text='Critical threshold for ping latency (ms)'),
        ),
        migrations.AddField(
            model_name='host',
            name='ping_critical_packet_loss',
            field=models.FloatField(default=20.0, help_text='Critical threshold for packet loss (%)'),
        ),
        migrations.AddField(
            model_name='host',
            name='ping_packet_count',
            field=models.IntegerField(default=4, help_text='Number of ping packets to send'),
        ),
        migrations.AddField(
            model_name='host',
            name='ping_timeout',
            field=models.IntegerField(default=5, help_text='Ping timeout in seconds'),
        ),
        migrations.AddField(
            model_name='host',
            name='ping_warning_latency',
            field=models.FloatField(default=100.0, help_text='Warning threshold for ping latency (ms)'),
        ),
        migrations.AddField(
            model_name='host',
            name='ping_warning_packet_loss',
            field=models.FloatField(default=5.0, help_text='Warning threshold for packet loss (%)'),
        ),
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('warning', 'Warning'), ('critical', 'Critical'), ('maintenance', 'Maintenance'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.CreateModel(
            name='PingResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('success', models.BooleanField()),
                ('latency', models.FloatField(blank=True, help_text='Average latency in milliseconds', null=True)),
                ('packet_loss', models.FloatField(default=0.0, help_text='Packet loss percentage')),
                ('packets_sent', models.IntegerField(default=0)),
                ('packets_received', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('up', 'Up'), ('warning', 'Warning'), ('critical', 'Critical'), ('down', 'Down')], max_length=20)),
                ('status_reason', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('check_duration', models.FloatField(blank=True, help_text='Time taken for ping check in seconds', null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ping_results', to='monitoring.host')),
            ],
            options={
                'verbose_name': 'Ping Result',
                'verbose_name_plural': 'Ping Results',
                'db_table': 'monitoring_ping_result',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['host', 'timestamp'], name='monitoring__host_id_5a1384_idx'), models.Index(fields=['status', 'timestamp'], name='monitoring__status_e83147_idx'), models.Index(fields=['timestamp'], name='monitoring__timesta_5b5b83_idx')],
            },
        ),
    ]
