# Generated by Django 5.1.4 on 2025-12-30 11:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_host_ping_critical_latency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('min_severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('email_enabled', models.BooleanField(default=True)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('telegram_enabled', models.BooleanField(default=False)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=100)),
                ('slack_enabled', models.BooleanField(default=False)),
                ('slack_channel', models.CharField(blank=True, max_length=100)),
                ('teams_enabled', models.BooleanField(default=False)),
                ('teams_webhook', models.URLField(blank=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('sms_number', models.CharField(blank=True, max_length=20)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Start of quiet hours (no notifications)', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='End of quiet hours', null=True)),
                ('quiet_hours_timezone', models.CharField(default='UTC', max_length=50)),
                ('escalation_enabled', models.BooleanField(default=True)),
                ('escalation_interval_minutes', models.IntegerField(default=30)),
                ('max_escalation_level', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_notification_profiles', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, related_name='notification_profiles', to='monitoring.devicegroup')),
                ('locations', models.ManyToManyField(blank=True, related_name='notification_profiles', to='monitoring.location')),
                ('users', models.ManyToManyField(blank=True, related_name='notification_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Profile',
                'verbose_name_plural': 'Notification Profiles',
                'db_table': 'monitoring_notification_profile',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EscalationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules are evaluated first')),
                ('condition_type', models.CharField(choices=[('time_based', 'Time Based'), ('severity_based', 'Severity Based'), ('location_based', 'Location Based'), ('group_based', 'Group Based'), ('check_type_based', 'Check Type Based')], max_length=20)),
                ('condition_config', models.JSONField(default=dict, help_text='Configuration for the condition')),
                ('escalation_interval_minutes', models.IntegerField(default=30)),
                ('max_escalation_level', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_escalation_rules', to=settings.AUTH_USER_MODEL)),
                ('level_1_profiles', models.ManyToManyField(blank=True, related_name='escalation_level_1_rules', to='monitoring.notificationprofile')),
                ('level_2_profiles', models.ManyToManyField(blank=True, related_name='escalation_level_2_rules', to='monitoring.notificationprofile')),
                ('level_3_profiles', models.ManyToManyField(blank=True, related_name='escalation_level_3_rules', to='monitoring.notificationprofile')),
            ],
            options={
                'verbose_name': 'Escalation Rule',
                'verbose_name_plural': 'Escalation Rules',
                'db_table': 'monitoring_escalation_rule',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=20)),
                ('recipient', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('escalation_level', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='monitoring.alert')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='monitoring.notificationprofile')),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'db_table': 'monitoring_notification_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['alert', 'status'], name='monitoring__alert_i_65b1a0_idx'), models.Index(fields=['channel', 'status'], name='monitoring__channel_3572dd_idx'), models.Index(fields=['sent_at'], name='monitoring__sent_at_d78fc4_idx'), models.Index(fields=['escalation_level'], name='monitoring__escalat_5e46e1_idx')],
            },
        ),
    ]
