# Generated by Django 5.1.4 on 2025-12-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_notificationprofile_escalationrule_notificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='http_urls',
            field=models.TextField(blank=True, help_text='One HTTP/HTTPS URL per line to monitor'),
        ),
        migrations.AddField(
            model_name='host',
            name='service_checks_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='host',
            name='snmp_auth_password',
            field=models.CharField(blank=True, help_text='SNMP v3 auth password', max_length=100),
        ),
        migrations.AddField(
            model_name='host',
            name='snmp_auth_protocol',
            field=models.CharField(blank=True, choices=[('', 'None'), ('MD5', 'MD5'), ('SHA', 'SHA')], help_text='SNMP v3 auth protocol', max_length=10),
        ),
        migrations.AddField(
            model_name='host',
            name='snmp_port',
            field=models.IntegerField(default=161, help_text='SNMP port number'),
        ),
        migrations.AddField(
            model_name='host',
            name='snmp_priv_password',
            field=models.CharField(blank=True, help_text='SNMP v3 privacy password', max_length=100),
        ),
        migrations.AddField(
            model_name='host',
            name='snmp_priv_protocol',
            field=models.CharField(blank=True, choices=[('', 'None'), ('DES', 'DES'), ('AES', 'AES')], help_text='SNMP v3 privacy protocol', max_length=10),
        ),
        migrations.AddField(
            model_name='host',
            name='snmp_username',
            field=models.CharField(blank=True, help_text='SNMP v3 username', max_length=100),
        ),
        migrations.AddField(
            model_name='host',
            name='tcp_ports',
            field=models.CharField(blank=True, help_text='Comma-separated list of TCP ports to monitor', max_length=500),
        ),
        migrations.AddField(
            model_name='host',
            name='udp_ports',
            field=models.CharField(blank=True, help_text='Comma-separated list of UDP ports to monitor', max_length=500),
        ),
    ]
