# Generated by Django 5.1.4 on 2025-12-31 05:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_add_snmp_and_service_monitoring_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveredDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('vendor', models.CharField(blank=True, max_length=100, null=True)),
                ('os_info', models.TextField(blank=True, null=True)),
                ('snmp_community', models.CharField(blank=True, max_length=100, null=True)),
                ('snmp_version', models.CharField(blank=True, max_length=10, null=True)),
                ('discovery_method', models.CharField(choices=[('ping', 'Ping Sweep'), ('snmp', 'SNMP Discovery'), ('port_scan', 'Port Scanning'), ('manual', 'Manual Entry'), ('import', 'Bulk Import')], default='ping', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('auto_approved', 'Auto-Approved'), ('ignored', 'Ignored')], default='pending', max_length=20)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_discoveries', to=settings.AUTH_USER_MODEL)),
                ('host', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovered_device', to='monitoring.host')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_discoveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discovered Device',
                'verbose_name_plural': 'Discovered Devices',
                'db_table': 'monitoring_discovered_device',
                'ordering': ['-discovered_at'],
                'indexes': [models.Index(fields=['ip_address'], name='monitoring__ip_addr_09ef1b_idx'), models.Index(fields=['status'], name='monitoring__status_4d2367_idx'), models.Index(fields=['discovered_at'], name='monitoring__discove_1c19a5_idx'), models.Index(fields=['device_type'], name='monitoring__device__af8873_idx')],
            },
        ),
    ]
