# Generated by Django 5.1.4 on 2025-12-31 11:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_add_discovered_device'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEscalation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_level', models.IntegerField(default=0)),
                ('last_escalation_time', models.DateTimeField(blank=True, null=True)),
                ('next_escalation_time', models.DateTimeField()),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledgment_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('alert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escalation', to='monitoring.alert')),
                ('escalation_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.escalationrule')),
            ],
            options={
                'verbose_name': 'Alert Escalation',
                'verbose_name_plural': 'Alert Escalations',
                'db_table': 'monitoring_alert_escalation',
                'indexes': [models.Index(fields=['next_escalation_time'], name='monitoring__next_es_28476f_idx'), models.Index(fields=['current_level'], name='monitoring__current_122497_idx'), models.Index(fields=['acknowledged'], name='monitoring__acknowl_0a3f1c_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlertEscalationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('escalation_level', models.IntegerField()),
                ('escalation_time', models.DateTimeField()),
                ('notification_results', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_history', to='monitoring.alert')),
                ('escalation_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.escalationrule')),
                ('notification_profiles', models.ManyToManyField(blank=True, to='monitoring.notificationprofile')),
            ],
            options={
                'verbose_name': 'Alert Escalation History',
                'verbose_name_plural': 'Alert Escalation History',
                'db_table': 'monitoring_alert_escalation_history',
                'ordering': ['-escalation_time'],
                'indexes': [models.Index(fields=['alert', 'escalation_time'], name='monitoring__alert_i_6287ad_idx'), models.Index(fields=['escalation_level'], name='monitoring__escalat_da350d_idx'), models.Index(fields=['escalation_time'], name='monitoring__escalat_bda30f_idx')],
            },
        ),
    ]
